name: Deploy to Siteground Hosting through SSH on push
'on':
  push:
    branches:
      - master
jobs:
  build_and_deploy:  
    runs-on: ubuntu-latest
    steps:    
    uses: actions/checkout@v2
    name: build
    run: npm ci --legacy-peer-deps && npm run build --legacy-peer-deps   
    uses: SamKirkland/FTP-Deploy-Action@4.3.0
    name: 📂 Sync files / deploy
    with:
      server: ${{ secrets.FTP_SERVER}}
      username: ${{ secrets.FTP_USERNAME}}
      password: ${{ secrets.FTP_PASSWORD }}
      server-dir: public_html/
      local-dir: build/

     